:: change sound plan

reg add "HKEY_CURRENT_USER\AppEvents\Schemes" /ve /d "scrue0" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\.Default\.Current" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\.Default\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\AppGPFault\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\CCSelect\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\ChangeTheme\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\Close\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\CriticalBatteryAlarm\.Current" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\CriticalBatteryAlarm\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\DeviceConnect\.Current" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\DeviceConnect\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\DeviceDisconnect\.Current" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\DeviceDisconnect\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\DeviceFail\.Current" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\DeviceFail\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\FaxBeep\.Current" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\FaxBeep\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\LowBatteryAlarm\.Current" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\LowBatteryAlarm\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\MailBeep\.Current" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\MailBeep\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\Maximize\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\MenuCommand\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\MenuPopup\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\MessageNudge\.Current" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\MessageNudge\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\Minimize\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\Notification.Default\.Current" /ve /d "C:\Windows\media\Ring10.wav" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\Notification.Default\scrue0" /ve /d "C:\Windows\media\Ring10.wav" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\Notification.IM\.Current" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\Notification.IM\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\Notification.Mail\.Current" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\Notification.Mail\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\Notification.Proximity\.Current" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\Notification.Proximity\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\Notification.Reminder\.Current" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\Notification.Reminder\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\Notification.SMS\.Current" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\Notification.SMS\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\Open\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\PrintComplete\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\ProximityConnection\.Current" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\ProximityConnection\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\RestoreDown\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\RestoreUp\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\ShowBand\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\SystemAsterisk\.Current" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\SystemAsterisk\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\SystemExclamation\.Current" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\SystemExclamation\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\SystemHand\.Current" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\SystemHand\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\SystemNotification\.Current" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\SystemNotification\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\SystemQuestion\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\WindowsUAC\.Current" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\.Default\WindowsUAC\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\Explorer\ActivatingDocument\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\Explorer\BlockedPopup\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\Explorer\EmptyRecycleBin\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\Explorer\FeedDiscovered\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\Explorer\MoveMenuItem\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\Explorer\Navigating\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\Explorer\SecurityBand\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\sapisvr\DisNumbersSound\.current" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\sapisvr\DisNumbersSound\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\sapisvr\HubOffSound\.current" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\sapisvr\HubOffSound\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\sapisvr\HubOnSound\.current" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\sapisvr\HubOnSound\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\sapisvr\HubSleepSound\.current" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\sapisvr\HubSleepSound\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\sapisvr\MisrecoSound\.current" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\sapisvr\MisrecoSound\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\sapisvr\PanelSound\.current" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Apps\sapisvr\PanelSound\scrue0" /ve /d "" /f >NUL
reg add "HKEY_CURRENT_USER\AppEvents\Schemes\Names\scrue0" /ve /d "scruel" /f >NUL

